### PR TITLE
Better map update

### PR DESCRIPTION
**Pull request by EvansMatthew97**
Map updater now finds reserves by name after selecting an area (this needs further testing)

It finds the following features:
Rivers
Intermittent water sources (those which are seasonal)
Dams
Roads
Residential and fenced areas

It also provides a partitioned map grid of cells, and calculates the distances to features for each of these cells.

### CODE REVIEW

**Comment by ASLouw** [comment]
Not finding Rietvlei reserve when updating map

**Comment by EvansMatthew97** [comment]
> Not finding Rietvlei reserve when updating map

Thanks I'll look into it

**Comment by EvansMatthew97** [comment]
Found the issue. The updater was looking for nodes, but Rietvlei appears to be a way.

An issue was also fixed where multi geometry was not working and causing incorrect calculations of distance.

**Comment by ASLouw** [comment]
Great, tested it seems to be working as expected.

**Comment by EvansMatthew97** [comment]
Also fixed an issue where overpass was rate limiting and returning 429. Now the updater handles it.

**Review by ASLouw — APPROVED** [review]
Seems to be working for most reserves

**Pull request merged**
